USE master;
GO

-- 1) Mata cualquier sesión pegada a esa BD
DECLARE @spid INT, @sql NVARCHAR(50);
DECLARE c CURSOR FOR
    SELECT spid FROM master..sysprocesses WHERE dbid = DB_ID('SAM_IMSS');
OPEN c;
FETCH NEXT FROM c INTO @spid;
WHILE @@FETCH_STATUS = 0
BEGIN
    SET @sql = N'KILL ' + CAST(@spid AS NVARCHAR(10));
    EXEC(@sql);
    FETCH NEXT FROM c INTO @spid;
END
CLOSE c; DEALLOCATE c;
GO

-- 2) Quitar SINGLE_USER (si se reconecta algo, usamos OFFLINE/ONLINE)
BEGIN TRY
    ALTER DATABASE [SAM_IMSS] SET MULTI_USER WITH ROLLBACK IMMEDIATE;
END TRY
BEGIN CATCH
    ALTER DATABASE [SAM_IMSS] SET OFFLINE WITH ROLLBACK IMMEDIATE;
    ALTER DATABASE [SAM_IMSS] SET ONLINE;
    ALTER DATABASE [SAM_IMSS] SET MULTI_USER;
END CATCH;
GO